### ISSUE TITLE
Access GoCD API with Google OAuth Plugin?

### ISSUE THREAD

**Issue by mattgauntseo-sentry** [gocd-contrib/google-oauth-authorization-plugin#189]
Is it possible to access the GoCD API with the Google OAuth plugin?

I know access tokens aren't supported (See: https://github.com/gocd-contrib/google-oauth-authorization-plugin/issues/60) but I was wondering if that prevents API access entirely, or does it just prevent use of tokens and there is another way to call the GoCD API?

**Comment by chadlwilson** [comment]
To my knowledge there's nothing that technically prevents that since plugins are just Java code, although I'm not sure if any plugins do so. You'd add plugin configuration that asks the user for a GoCD access token during config and then make API calls with that similar to how this plugin talks to Google or other services using their access codes or oauth2 client secrets.

Depending on the particular server request to plugin that was making the call it might not lead to the best experience per se, but don't see anything that would prevent it.

**Comment by chadlwilson** [comment]
After re-reading perhaps I misunderstood your message. If you mean access to the API for a *user* authenticated with the Google OAuth2 plugin (rather than the plugin itself) then yes, I think it would prevent this unless you added an additional authorization configuration with a different plugin.

**Comment by mattgauntseo-sentry** [comment]
Yeah sorry, this was more of a question of a user making an API call to the GoCD server using a <insert auth header solution>.

**Comment by chadlwilson** [comment]
Possibly similar to this thread, although in that case the user is trying to get working a plugin that in theory should support PATs: https://groups.google.com/g/go-cd/c/0mm8AfGs1ho

**Comment by chadlwilson** [comment]
Possibly similar to this thread, although in that case the user is trying to get working a plugin that in theory should support PATs: https://groups.google.com/g/go-cd/c/0mm8AfGs1ho
